from typing import Annotated, Any
from typing_extensions import TypedDict
from langgraph.graph.message import add_messages


class AgentState(TypedDict):
    # Conversation history (auto-appended by add_messages reducer)
    messages: Annotated[list, add_messages]

    # Raw transcript from user (voice STT or text input)
    transcript: str

    # Which skill was selected by the router
    selected_skill: str

    # The response generated by the skill executor
    response_text: str

    # The user's email address (if known)
    user_email: str

    # User identifier for memory
    user_id: str

    # Source channel: "api" | "webhook" | "wechat"
    channel: str

    # Any error message to surface to the user
    error: str | None
